# Generated by Django 2.2.17 on 2021-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=65536)),
                ('featured', models.IntegerField(choices=[(1, 'inactive'), (3, 'active'), (2, 'featured')], default=1, help_text='Inactive = not displayed, Active = Displayed everywhere except Featured page, Featured = Displayed everywhere including Featured page', verbose_name='Display')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=65536)),
                ('featured', models.IntegerField(choices=[(1, 'inactive'), (3, 'active'), (2, 'featured')], default=1, help_text='Inactive = not displayed, Active = Displayed everywhere except Featured page, Featured = Displayed everywhere including Featured page', verbose_name='Display')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
