# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 23:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180808_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, help_text='Model Image', null=True, upload_to='images', verbose_name='Index Page Image')),
                ('wide_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Detail Page Image')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text="URL key for the instance (automatically populated from title). You should generally not change this field as you'll break deep links to the instance.", populate_from='generate_slug', unique=True)),
                ('body', tinymce.models.HTMLField(blank=True, max_length=65536, null=True)),
                ('short_description', models.CharField(default='', help_text='Brief description to show in smaller content areas', max_length=500)),
                ('featured', models.IntegerField(choices=[(1, 'inactive'), (3, 'active'), (2, 'featured')], default=1, help_text='Inactive = not displayed, Active = Displayed everywhere except Featured page, Featured = Displayed everywhere including Featured page', verbose_name='Display')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
