# Generated by Django 2.2.17 on 2021-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='body',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
    ]
